export const GET_TODO_LISTS_REQUEST = 'GET_TODO_LISTS_REQUEST';
export const GET_TODO_LISTS_SUCCESS = 'GET_TODO_LISTS_SUCCESS';
export const GET_TODO_LISTS_FAILURE = 'GET_TODO_LISTS_FAULIAR';

export const ADD_TODO_REQUEST = 'GET_TODO_REQUEST';
export const ADD_TODO_SUCCESS = 'GET_TODO_SUCCESS';
export const ADD_TODO_FAILURE = 'ADD_TODO_FAULIAR';

export const TOGGLE_TODO_REQUEST = 'TOGGLE_TODO_REQUEST';
export const TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS';
export const TOGGLE_TODO_FAILURE = 'TOGGLE_TODO_FAULIAR';