export const ADD_COUNT='ADD_COUNT';
export const SUB_COUNT='SUB_COUNT';

export const GET_TODO_REQUEST = 'GET_TODO_REQUEST';
export const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS';
export const GET_TODO_FAILURE = 'GET_TODO_FAILURE';